import = [
  "~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml",
]

[window]
decorations = "None"
padding = {x = 3, y = 0}

[font]
normal = {family = "Hack Nerd Font Mono", style = "Regular"}
size = 12

[env]
TERM = "xterm-256color"
