import = [
  "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml",
]

[window]
decorations = "None"
padding = {x = 3, y = 0}
startup_mode = "Fullscreen"

[font]
normal = {family = "Hack Nerd Font Mono", style = "Regular"}
size = 12

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  {key = "F11", action = "ToggleFullscreen"},
  {key = "Q", mods = "Control", action = "Quit"},
]
